console.log('I am sorry')
console.log('You are sorry')
console.log('she is sorry')
console.log('I am in ecothone')
console.log('Sorry, i make project for hackaton')
console.log('today i coder 24hours')
console.log('today i relax')